dataset_files:
- data\synthetic_parallel\d1.csv
total_samples: 5576
train_pool_size: 4739
test_set_size: 837
model_name: ai4bharat/IndicBART
hyperparameters:
  epochs: 5
  batch_size: 16
  gradient_accumulation_steps: 2
  effective_batch_size: 32
  learning_rate: 5.0e-05
  weight_decay: 0.01
  warmup_ratio: 0.1
  early_stopping_patience: 2
n_folds: 5
avg_val_loss: 1.0499
avg_val_bleu: 47.1446
avg_val_chrf: 77.2438
avg_test_loss: 1.0387
avg_test_bleu: 48.5423
avg_test_chrf: 78.3542
fold_metrics:
- fold: 1
  train_samples: 3792
  val_samples: 947
  train_loss: 3.8249
  val_loss: 1.0745
  val_bleu: 46.9892
  val_chrf: 77.3437
  test_loss: 1.0413
  test_bleu: 48.5162
  test_chrf: 78.4909
- fold: 2
  train_samples: 3792
  val_samples: 947
  train_loss: 3.836
  val_loss: 1.0512
  val_bleu: 47.1665
  val_chrf: 77.2242
  test_loss: 1.0383
  test_bleu: 48.6625
  test_chrf: 78.2704
- fold: 3
  train_samples: 3792
  val_samples: 947
  train_loss: 3.8466
  val_loss: 1.046
  val_bleu: 47.7623
  val_chrf: 77.7589
  test_loss: 1.0393
  test_bleu: 48.3186
  test_chrf: 78.3562
- fold: 4
  train_samples: 3792
  val_samples: 947
  train_loss: 3.8275
  val_loss: 1.0489
  val_bleu: 46.7639
  val_chrf: 77.1364
  test_loss: 1.0396
  test_bleu: 48.6459
  test_chrf: 78.3703
- fold: 5
  train_samples: 3788
  val_samples: 951
  train_loss: 3.8359
  val_loss: 1.0289
  val_bleu: 47.0412
  val_chrf: 76.7559
  test_loss: 1.0351
  test_bleu: 48.5684
  test_chrf: 78.2834
